import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TIER 11",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <header>
          <ul>
            <li><a href="/sobre"> Sobre</a></li>
            <li><a href="/sobre/empresa">Empresa</a></li>
            <li> <Link href={"/"}> Pagina inicial</Link></li>
          </ul>
        </header>

        
        {children}

        <footer>

          <ul>
            <li>Instagram</li>
            <li>Facebook</li>
            <li>Linkedin</li>
          </ul>

          </footer>

        
      </body>
    </html> 
  );
}
